---
# tasks file for orcle client
- name: install needed software
  yum:
    name: "{{item}}"
  when: ansible_distribution != "AIX"
  with_items:
    - libstdc++.i686
    - glibc.i686
    - xdpyinfo
    - compat-libcap1
    - compat-libstdc++-33
    - sysstat
    - gcc
    - gcc-c++
    - ksh
    - glibc-devel
    - libaio-devel
    - nfs-utils
    - rpcbind
    - tcsh
    - glibc-devel.i686
    - libgcc.i686
    - libstdc++-devel.i686
    - ncurses-devel.i686
    - libaio.i686
    - libaio-devel.i686

- name: enable nfs-related services
  service:
   name: "{{ item }}"
   enabled: true
   state: started
  with_items:
  - rpcbind
  - nfs-lock
  when: ansible_distribution != "AIX"

- name: mount repository on linux
  mount:
    name: "/mnt{{ software_repository_path }}"
    src: "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}:{{ software_repository_path }}"
    fstype: nfs
    state: mounted
  when: ansible_distribution != "AIX"

- name: mount repository on aix
  command: /usr/sbin/mknfsmnt -f "/mnt{{ software_repository_path }}" -d "{{ software_repository_path }}" -h "{{ hostvars[groups['repository-server'][0]]['ansible_default_ipv4']['address'] }}" -M sys -N -a -t rw -w bg -Y -Z -X -H -j -q -g
  when: ansible_distribution == "AIX"

- name: create groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sse_role
    - oinstall
    - dba
    - oper

- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: sse_role
    groups: sse_role,oinstall
  with_items:
    - siebel

- name: create siebel .bash_profile
  blockinfile:
    path: /home/siebel/.bash_profile
    create: yes
    owner: siebel
    group: sse_role
    block: |
       # Oracle Settings
       TMP={{siebel_base_path}}/tmp; export TMP
       TMPDIR=$TMP; export TMPDIR
       ORACLE_BASE={{siebel_base_path}}/oracle_client; export ORACLE_BASE
       ORACLE_HOME={{siebel_base_path}}/oracle_client/client; export ORACLE_HOME
       ORACLE_SID=orcl; export ORACLE_SID
       PATH=/usr/sbin:$PATH; export PATH
       PATH=$ORACLE_HOME/bin:$PATH; export PATH
       LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
       export LIBPATH=$LD_LIBRARY_PATH
       RESOLV_MULTI=off ; export RESOLV_MULTI


 
- name: create user
  user:
    name: "{{ item }}"
    state: present
    group: oinstall
    groups: oinstall,dba,oper
  with_items:
    - oracle

- name: create oracle .bash_profile
  blockinfile:
    path: /home/oracle/.bash_profile
    create: yes
    owner: oracle
    group: oinstall
    block: |
      # Oracle Settings
      TMP={{oracle_base_path}}/tmp; export TMP
      TMPDIR=$TMP; export TMPDIR
      ORACLE_HOSTNAME={{ ansible_hostname }}; export ORACLE_HOSTNAME
      ORACLE_UNQNAME=orcl; export ORACLE_UNQNAME
      ORACLE_BASE={{oracle_base_path}}/base; export ORACLE_BASE
      ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1; export ORACLE_HOME
      ORACLE_SID=orcl; export ORACLE_SID
      PATH=/usr/sbin:$PATH; export PATH
      PATH=$ORACLE_HOME/bin:$PATH; export PATH
      LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib; export LD_LIBRARY_PATH
      export LIBPATH=$LD_LIBRARY_PATH	  
      CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib; export CLASSPATH

- name: set limit_items
  set_fact:
    limit_items:  [ 'nproc', 'nproc' , 'nofile', 'nofile' , 'stack' ]
    limit_types:  [ 'soft' , 'hard'  , 'soft'  , 'hard'   , 'soft' ]
    limit_values: [ '2047' , '16384' , '4096'  , '65536'  , '10240' ]

- name: set os limits for user
  pam_limits:
    domain: oracle
    limit_item: "{{ item.0 }}"
    limit_type: "{{ item.1 }}"
    value: "{{ item.2 }}"
  with_together:
    - "{{ limit_items }}"
    - "{{ limit_types }}"
    - "{{ limit_values }}"  
  when: ansible_distribution != "AIX"
  
- name: set os limits for user on AIX
  command: "chuser {{item}}=-1 oracle"
  with_items:
    - "fsize"
    - "data"
    - "stack"
    - "core"
    - "rss"
    - "nofiles"
    - "threads"
    - "nproc"
    - "cpu_hard"
    - "fsize_hard"
    - "data_hard"
    - "stack_hard"
    - "core_hard"
    - "rss_hard"
    - "nofiles_hard"
    - "threads_hard"
    - "nproc_hard"
  when: ansible_distribution == "AIX"
  
- name: set sysctl_items
  set_fact:
    sysctl_items:  ['fs.suid_dumpable','fs.aio-max-nr','fs.file-max','kernel.shmall','kernel.shmmax','kernel.shmmni','kernel.sem','net.ipv4.ip_local_port_range','net.core.rmem_default','net.core.rmem_max','net.core.wmem_default','net.core.wmem_max' ]
    sysctl_values:  [ '1','1048576','6815744','2097152','2271385600','4096','250 32000 100 128','9000 65500','262144','4194304','262144','1048586']
  when: ansible_distribution != "AIX"

- name: set sysctl settings
  sysctl:
    name: "{{item.0}}"
    value: "{{item.1}}"
    sysctl_set: yes
    state: present
    reload: yes
  with_together:
    - "{{ sysctl_items }}"
    - "{{ sysctl_values }}"
  when: ansible_distribution != "AIX"

- name: set selinux to premissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution != "AIX"

- name: disable firewall
  service:
   name: "{{ item }}"
   enabled: false
   state: stopped
  with_items:
  - firewalld
  when: ansible_distribution != "AIX"

- name: copy UnlimitedJCEPolicyJDK8 files
  copy:
    src: "{{ software_repository_path }}/jce/unarchive/UnlimitedJCEPolicyJDK8/{{item}}"
    dest: "{{java_home}}/jre/lib/security/"
    remote_src: true
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  when: ansible_distribution != "AIX"
